### ISSUE TITLE
Enable Siren or play audio through HomeAssistant

### ISSUE THREAD

**Issue by alej908** [g8keeperzuul/wz_mini_hacks-MQTT#6]
From the info page:
"With the exception of playing a sound, updating the refresh rate and enabling or disabling the web console, ALL other changes in state require that the camera be rebooted before the change takes effect. "

Can a sound or the siren be enabled through this mqtt integration with HomeAssistant?  I'd love to incorporate automations using frigate for person detection in a zone and play the siren or some other audio. If it is possible, how can it be done? Would HomeAssistant see it as a media player?

**Comment by g8keeperzuul** [comment]
1. Verify that wz_mini_hacks works and you can indeed play a sound through the camera.
There are a number of audio files already on the device, so we can test with one of those. For a list of available files see [mqtt-control.sh line 25](https://github.com/g8keeperzuul/wz_mini_hacks-MQTT/blob/bb60206d011cf9cb18e2896439bac30af45055a2/bin/mqtt-control.sh#L25). 
1.1 ssh to your camera
1.2 ```$ cmd aplay /system/local/siren.wav 50```

If the wz_mini_hacks verification works, then the next step is to do the same, but via MQTT.

2. From your laptop:
    ```$ mosquitto_pub -L mqtt://USER:PASSWORD@MQTT_BROKER_HOST:1883/homeassistant/camera/CUSTOM_HOSTNAME/play -m "/system/local/siren.wav 50"```

Where CUSTOM_HOSTNAME comes from /opt/wz_mini/wz_mini.conf

3. The final step is to create a Home Assistant automation that sends an MQTT message in the form ```"<AUDIOFILENAME> <VOLUME>"``` to the topic "/homeassistant/camera/CUSTOM_HOSTNAME/play"
Where VOLUME is an integer 1..100

**Comment by alej908** [comment]
Wow! Thank you, I plan to try this soon!

**Comment by Marcoske23** [comment]
> 

Hi!
Hello! I was following the steps you mention and until the first one plays the sound. At the moment I use MQTT with MQTT explorer, It doesn't work.
Topic:
> homeassistant/camera/Wyze-Sala/play
 
with the payload "/opt/wz_mini/usr/share/audio/swap.wav 100" (with quotation marks) does not play. Is there any more consideration I should have?
![image](https://user-images.githubusercontent.com/103160819/213944268-ec7a490d-bf93-405f-83a2-447cc280a517.png)
![image](https://user-images.githubusercontent.com/103160819/213944331-6993fed6-8489-4698-8183-bc230d0838f6.png)

**Comment by g8keeperzuul** [comment]
Q1: Did you successfully hear the audio when running step #1.2?
Q2: Was "Wyze-Sala" defined as the CUSTOM_HOSTNAME in  /opt/wz_mini/wz_mini.conf ?
Q3: Did you verify that /opt/wz_mini/usr/share/audio/swap.wav exists on your device?
